version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - '386'
    ignore:
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format_overrides:
    - goos: windows
      formats: ['zip']

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
  draft: false

homebrew_casks:
  - name: nekot 
    ids:
      - nekot
    repository:
      owner: BalanceBalls
      name: homebrew-BalanceBalls
    homepage: https://github.com/BalanceBalls/nekot
    commit_author:
      name: BalanceBalls
    skip_upload: auto
