builds:
  - id: darwin-amd64-chatgpt-tui
    main: ./
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - pkg_config_sysroot_dir=/sysroot/macos/amd64
      - pkg_config_path=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      - cc=o64-clang
      - cxx=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -x main.version={{.version}}
    binary: bin/rc-chatgpt-tui
    
  - id: darwin-amd64-nekot
    main: ./
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - pkg_config_sysroot_dir=/sysroot/macos/amd64
      - pkg_config_path=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      - cc=o64-clang
      - cxx=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -x main.version={{.version}}
    binary: bin/rc-nekot

archives:
  - id: rc-nekot
    builds:
      - darwin-amd64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    wrap_in_directory: true

  - id: rc-chatgpt-tui
    builds:
      - darwin-amd64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: zip
    wrap_in_directory: true

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
  draft: false

brews:
  - name: rc-nekot
    ids:
      - rc-nekot
    tap:
      owner: tearingItUp786
      name: homebrew-tearingitup786
    homepage: https://github.com/tearingItUp786/chatgpt-tui
    commit_author:
      name: tearingitup786

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    #
    # Templates: allowed
    skip_upload: false

  - name: rc-chatgpt-tui
    ids:
      - rc-chatgpt-tui
    tap:
      owner: tearingItUp786
      name: homebrew-tearingitup786
    homepage: https://github.com/tearingItUp786/chatgpt-tui
    commit_author:
      name: tearingitup786

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    #
    # Templates: allowed
    skip_upload: false
    post_install: |
      opoo "⚠︎ rc-chatgpt-tui is deprecated and will be removed in the future. Use rc-nekot instead."
