# 130x50
Output nekot.mp4

Require echo

Set Shell "zsh"
Set Theme "ayu"
Set Height 1600
Set Width 2000
Set Framerate 30
Set PlaybackSpeed 0.35
Set TypingSpeed 100ms
Set Margin 15
Set MarginFill "#98971a"
Set BorderRadius 15
Set Padding 5

Hide
Type "./nekot"
Enter
Show

Sleep 3s

Type "3"
Sleep 1s

Type "m"
Sleep 1s

Type "/"
Sleep 1s

Type "gemini-2.0-flash"
Sleep 1s

Enter
Sleep 1s

Enter
Sleep 1s

Type "1"
Sleep 1s

Type "i"
Sleep 1s

Type "Explain the following go code:"
Sleep 0.5s
Ctrl+e
Sleep 0.5s
Type "i"
Sleep 0.5s
Enter
Sleep 0.5s
Type "```go"
Enter
Sleep 0.5s

Ctrl+v
Sleep 0.5s

Enter
Type "```"
Sleep 0.5s

Escape
Sleep 1s
Enter

Sleep 7s

Type "2"
Sleep 1s

Space
Sleep 1s

Type "kkkk"
Sleep 1s

Space
Sleep 1s

Type "3j"
Sleep 1s
Type "9j"
Sleep 2s

Type "y"
Sleep 3s

Escape
Sleep 2s

Ctrl+n
Sleep 2s
